version: "3"
services:

  db:
    container_name: db
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD_FILE: /etc/wiki/.db-secret
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /etc/wiki/.db-secret:/etc/wiki/.db-secret:ro
    networks:
      - wikinet

  wiki:
    container_name: wiki
    image: solareenlo/wiki:latest
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS_FILE: /etc/wiki/.db-secret
      DB_NAME: wiki
      UPGRADE_COMPANION: 1
      LETSENCRYPT_DOMAIN: 42cursus.dev
      LETSENCRYPT_EMAIL: 42cursus@protonmail.com
      SSL_ACTIVE: 1
    volumes:
      - /etc/wiki/.db-secret:/etc/wiki/.db-secret:ro
    restart: unless-stopped
    ports:
      - "80:3000"
      - "443:3443"
    networks:
      - wikinet

networks:
  wikinet:
    external: true

volumes:
  pgdata:
